apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets-external
  namespace: taskmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: INTERNAL_API_KEY
      remoteRef:
        key: taskmanager/app
        property: internal_api_key
